/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Employeers/Auth.vue')['default']
    AuthPage: typeof import('./components/Employeers/AuthPage.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    OrderForm: typeof import('./components/Client/OrderForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
  }
}
