/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveOrderPage: typeof import('./components/Employeers/DashBoard/ActiveOrderPage.vue')['default']
    ArchivePage: typeof import('./components/Employeers/DashBoard/ArchivePage.vue')['default']
    AsideMenu: typeof import('./components/Employeers/AsideMenu.vue')['default']
    AuthPage: typeof import('./components/Employeers/AuthPage.vue')['default']
    ClientsPage: typeof import('./components/Employeers/DashBoard/ClientsPage.vue')['default']
    EmployeersPage: typeof import('./components/Employeers/DashBoard/EmployeersPage.vue')['default']
    MainDashboard: typeof import('./components/Employeers/DashBoard/MainDashboard.vue')['default']
    OrderForm: typeof import('./components/Client/OrderForm.vue')['default']
    OrderModal: typeof import('./components/Employeers/DashBoard/OrderModal.vue')['default']
    PremisePage: typeof import('./components/Employeers/DashBoard/PremisePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
  }
}
